### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by celiazut** [aroelke/deck-editor#3]
Hi,
After resolving encoding errors I still have some errors during maven compilation. It's mostly errors about types :
`[ERROR] .../deck-editor/MTG Deck Editor/src/editor/database/characteristics/ManaType.java:[111,64] array required, but java.util.List<editor.database.characteristics.ManaType> found`

Do you have them ? 
Do you think I miss some step during the initialization of the project ?

I found a way to correct them http://stackoverflow.com/questions/20067956/array-required-but-arrayliststring-found but I would like to make sure I don't miss something before begin : there is almost 100 errors of this type.

Thanks!

**Comment by aroelke** [comment]
That's probably because of the java-oo requirement, which adds some rudimentary operator overloading.  I pretty much only use it for list and map accesses, but I think it improves code readability by a lot.  I use Eclipse, so I have it installed as a plugin which is why it isn't part of the pom.xml.

**Comment by celiazut** [comment]
You're right, I now use eclipse with the java-oo plugin and it's work ! 
Thanks
